---
- name: Configure Cloud City Instance
  hosts: ec2
  become: true  # Run as sudo
  gather_facts: true
  vars:
    app_repo_url: "https://github.com/thepm-cpu/cloud-city.git"  # Replace with your repo URL 
   
  roles:
    - app
    - monitoring