---
- name: Configure Cloud City Instance
  hosts: ec2
  become: true  # Run as sudo
  gather_facts: true
  vars:
    app_repo_url: "https://github.com/thepm-cpu/cloud-city.git"  # Replace with your repo URL 
    
  roles:
    - app
    - monitoring

- name: Configure Cloud City Instance
  hosts: ec2
  become: true
  vars:
    ansible_connection: amazon.aws.aws_ssm
    ansible_aws_ssm_bucket: "{{ ansible_s3_bucket }}"  # From Terraform output
    ansible_aws_ssm_region: "eu-north-1"
    ansible_aws_ssm_timeout: 60   