name: Deploy Cloud City

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-north-1
      TF_BACKEND_BUCKET: cloud-city-tf-state

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -backend-config="bucket=${{ env.TF_BACKEND_BUCKET }}" -backend-config="key=cloud-city.tfstate" -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -out=plan.tfout

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve plan.tfout

      - name: Get EC2 Outputs
        id: get-outputs
        working-directory: terraform
        run: |
          echo "EC2_INSTANCE_ID=$(terraform output -raw ec2_instance_id)" >> $GITHUB_OUTPUT
          echo "ANSIBLE_S3_BUCKET=$(terraform output -raw ansible_s3_bucket)" >> $GITHUB_OUTPUT

      - name: Install required Python libs for Ansible AWS collection
        run: |
          pipx runpip ansible-core install boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Run Ansible Playbook
        working-directory: ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          echo "[ec2]" > inventory.ini
          echo "${{ steps.get-outputs.outputs.EC2_INSTANCE_ID }} ansible_connection=amazon.aws.aws_ssm ansible_aws_ssm_bucket=${{ steps.get-outputs.outputs.ANSIBLE_S3_BUCKET }} ansible_aws_ssm_region=eu-north-1 ansible_user=ubuntu" >> inventory.ini
          ansible-playbook -i inventory.ini playbook.yml